### ISSUE TITLE
Background white on PHP storm 2016.1.1

### ISSUE THREAD

**Issue by ZiperRom1** [abhimanyusharma003/phpstorm-spacegray#10]
In both theme, background for php files is white.

**Comment by ajuchacko91** [comment]
In both theme, background for php files is white. I have the same problem please do something love this theme, and can't wait to update phpstorm. Happy @ZiperRom1 already raised issue  to @abhimanyusharma003

**Comment by abhimanyusharma003** [comment]
Many thanks for reporting.
Check the new update #de2eaba

**Comment by ajuchacko91** [comment]
It works. Pleasure is all mine. thank you:)

**Comment by ZiperRom1** [comment]
it works, thanks.
