### ISSUE TITLE
Font size issues with hidpi compatibility

### ISSUE THREAD

**Issue by jkudish** [abhimanyusharma003/phpstorm-spacegray#5]
I've just upgraded to a new hidpi laptop, and re-installed phpstorm and phpstorm-spacegray from scratch. Every time I re-open Phpstorm, the font size resets to either 64 or 128, way too big to comfortably code, even though I have set it to 16 and the setting persists while phpstorm is open. This problem doesn't happen if I use a different color scheme.

Any ideas?

**Comment by abhimanyusharma003** [comment]
This is strange, to install [Source Code Pro] (https://www.google.com/fonts/specimen/Source+Code+Pro) font see it works fine. May be your system is missing that font.

**Comment by jkudish** [comment]
Thanks for the quick response. Yeah quite strange indeed. The font is correctly installed and loading and I haven't changed the font setting. Any other suggestions?

**Comment by abhimanyusharma003** [comment]
I have updated the theme recently, can you please check again by downloading it again. ( Overwrite the theme files by closing phpstorm )

I'm not sure what causing it I have exported the theme from the default settings.

You can also visit phpStorm installation folder then in bin search for `PhpStorm64.exe.vmoptions` and `PhpStorm.exe.vmoptions` place these lines in it.

```
-Dawt.useSystemAAFontSettings=lcd
-Dawt.java2d.opengl=true
```

If these lines do nothing they will still speed up your phpStorm.

**Comment by jkudish** [comment]
I am running Linux (Fedora 22 to be specific). I guess I should have specified that :)

I'll try the updated theme in a moment.

**Comment by jkudish** [comment]
The latest version of the theme doesn't have the problem anymore. Thanks so much for your help.
